name: Automatizacion prueba

on:
  schedule:
    - cron: "0 10 * * *"  # todos los días
  workflow_dispatch: # para ejecutarlo manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Ejecutar script
        run: python script.py